### ISSUE TITLE
Twitter don't allow auto liking...

### ISSUE THREAD

**Issue by va3093** [martinm/twitter-like-bot#3]
Have you seen this in the developer guidelines. Have you had accounts blocked due to auto liking.
<img width="615" alt="screen shot 2018-09-22 at 16 16 46" src="https://user-images.githubusercontent.com/8058892/45918717-2d9c2080-be83-11e8-8b08-310dd712cc0d.png">

**Comment by va3093** [comment]
From https://help.twitter.com/en/rules-and-policies/twitter-automation

**Comment by martinm** [comment]
Twitter changed all the rules recently, this repo was created long time ago. I do not plan to update anything here.
